// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myproto.proto

package com.example.mqttkotlinsample;

import java.io.Serializable;

public final class Myproto implements Serializable {

  public Myproto() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.mqttkotlinsample.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * in 1/10th microdegrees [-900000000,900000001]
     * </pre>
     *
     * <code>int32 latitude = 1;</code>
     * @return The latitude.
     */
    int getLatitude();

    /**
     * <pre>
     * in 1/10th microdegrees [-1799999999,1800000001]
     * </pre>
     *
     * <code>int32 longitude = 2;</code>
     * @return The longitude.
     */
    int getLongitude();
  }
  /**
   * Protobuf type {@code com.example.mqttkotlinsample.Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.mqttkotlinsample.Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Position();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              latitude_ = input.readInt32();
              break;
            }
            case 16: {

              longitude_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Myproto.internal_static_com_example_mqttkotlinsample_Position_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Myproto.internal_static_com_example_mqttkotlinsample_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Position.class, Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private int latitude_;
    /**
     * <pre>
     * in 1/10th microdegrees [-900000000,900000001]
     * </pre>
     *
     * <code>int32 latitude = 1;</code>
     * @return The latitude.
     */
    @Override
    public int getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private int longitude_;
    /**
     * <pre>
     * in 1/10th microdegrees [-1799999999,1800000001]
     * </pre>
     *
     * <code>int32 longitude = 2;</code>
     * @return The longitude.
     */
    @Override
    public int getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0) {
        output.writeInt32(1, latitude_);
      }
      if (longitude_ != 0) {
        output.writeInt32(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, latitude_);
      }
      if (longitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Position)) {
        return super.equals(obj);
      }
      Position other = (Position) obj;

      if (getLatitude()
          != other.getLatitude()) return false;
      if (getLongitude()
          != other.getLongitude()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.mqttkotlinsample.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.mqttkotlinsample.Position)
        PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Myproto.internal_static_com_example_mqttkotlinsample_Position_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Myproto.internal_static_com_example_mqttkotlinsample_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Position.class, Builder.class);
      }

      // Construct using com.example.mqttkotlinsample.Myproto.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        latitude_ = 0;

        longitude_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Myproto.internal_static_com_example_mqttkotlinsample_Position_descriptor;
      }

      @Override
      public Position getDefaultInstanceForType() {
        return Position.getDefaultInstance();
      }

      @Override
      public Position build() {
        Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Position buildPartial() {
        Position result = new Position(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Position) {
          return mergeFrom((Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Position other) {
        if (other == Position.getDefaultInstance()) return this;
        if (other.getLatitude() != 0) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int latitude_ ;
      /**
       * <pre>
       * in 1/10th microdegrees [-900000000,900000001]
       * </pre>
       *
       * <code>int32 latitude = 1;</code>
       * @return The latitude.
       */
      @Override
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * in 1/10th microdegrees [-900000000,900000001]
       * </pre>
       *
       * <code>int32 latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(int value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in 1/10th microdegrees [-900000000,900000001]
       * </pre>
       *
       * <code>int32 latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <pre>
       * in 1/10th microdegrees [-1799999999,1800000001]
       * </pre>
       *
       * <code>int32 longitude = 2;</code>
       * @return The longitude.
       */
      @Override
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * in 1/10th microdegrees [-1799999999,1800000001]
       * </pre>
       *
       * <code>int32 longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(int value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in 1/10th microdegrees [-1799999999,1800000001]
       * </pre>
       *
       * <code>int32 longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.mqttkotlinsample.Position)
    }

    // @@protoc_insertion_point(class_scope:com.example.mqttkotlinsample.Position)
    private static final Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Position();
    }

    public static Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @Override
    public Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientIdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.mqttkotlinsample.ClientIdentity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 clientId = 175;</code>
     * @return The clientId.
     */
    int getClientId();

    /**
     * <code>string entityType = 2;</code>
     * @return The entityType.
     */
    String getEntityType();
    /**
     * <code>string entityType = 2;</code>
     * @return The bytes for entityType.
     */
    com.google.protobuf.ByteString
        getEntityTypeBytes();
  }
  /**
   * Protobuf type {@code com.example.mqttkotlinsample.ClientIdentity}
   */
  public static final class ClientIdentity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.mqttkotlinsample.ClientIdentity)
      ClientIdentityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientIdentity.newBuilder() to construct.
    private ClientIdentity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientIdentity() {
      entityType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientIdentity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientIdentity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              String s = input.readStringRequireUtf8();

              entityType_ = s;
              break;
            }
            case 1400: {

              clientId_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Myproto.internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Myproto.internal_static_com_example_mqttkotlinsample_ClientIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientIdentity.class, Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 175;
    private int clientId_;
    /**
     * <code>uint32 clientId = 175;</code>
     * @return The clientId.
     */
    @Override
    public int getClientId() {
      return clientId_;
    }

    public static final int ENTITYTYPE_FIELD_NUMBER = 2;
    private volatile Object entityType_;
    /**
     * <code>string entityType = 2;</code>
     * @return The entityType.
     */
    @Override
    public String getEntityType() {
      Object ref = entityType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        entityType_ = s;
        return s;
      }
    }
    /**
     * <code>string entityType = 2;</code>
     * @return The bytes for entityType.
     */
    @Override
    public com.google.protobuf.ByteString
        getEntityTypeBytes() {
      Object ref = entityType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        entityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, entityType_);
      }
      if (clientId_ != 0) {
        output.writeUInt32(175, clientId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, entityType_);
      }
      if (clientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(175, clientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientIdentity)) {
        return super.equals(obj);
      }
      ClientIdentity other = (ClientIdentity) obj;

      if (getClientId()
          != other.getClientId()) return false;
      if (!getEntityType()
          .equals(other.getEntityType())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId();
      hash = (37 * hash) + ENTITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEntityType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientIdentity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientIdentity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientIdentity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientIdentity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientIdentity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientIdentity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientIdentity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientIdentity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientIdentity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientIdentity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientIdentity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientIdentity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientIdentity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.mqttkotlinsample.ClientIdentity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.mqttkotlinsample.ClientIdentity)
        ClientIdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Myproto.internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Myproto.internal_static_com_example_mqttkotlinsample_ClientIdentity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientIdentity.class, Builder.class);
      }

      // Construct using com.example.mqttkotlinsample.Myproto.ClientIdentity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        clientId_ = 0;

        entityType_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Myproto.internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor;
      }

      @Override
      public ClientIdentity getDefaultInstanceForType() {
        return ClientIdentity.getDefaultInstance();
      }

      @Override
      public ClientIdentity build() {
        ClientIdentity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientIdentity buildPartial() {
        ClientIdentity result = new ClientIdentity(this);
        result.clientId_ = clientId_;
        result.entityType_ = entityType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientIdentity) {
          return mergeFrom((ClientIdentity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientIdentity other) {
        if (other == ClientIdentity.getDefaultInstance()) return this;
        if (other.getClientId() != 0) {
          setClientId(other.getClientId());
        }
        if (!other.getEntityType().isEmpty()) {
          entityType_ = other.entityType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientIdentity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientIdentity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clientId_ ;
      /**
       * <code>uint32 clientId = 175;</code>
       * @return The clientId.
       */
      @Override
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>uint32 clientId = 175;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(int value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 clientId = 175;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = 0;
        onChanged();
        return this;
      }

      private Object entityType_ = "";
      /**
       * <code>string entityType = 2;</code>
       * @return The entityType.
       */
      public String getEntityType() {
        Object ref = entityType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          entityType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string entityType = 2;</code>
       * @return The bytes for entityType.
       */
      public com.google.protobuf.ByteString
          getEntityTypeBytes() {
        Object ref = entityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          entityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string entityType = 2;</code>
       * @param value The entityType to set.
       * @return This builder for chaining.
       */
      public Builder setEntityType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        entityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string entityType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntityType() {
        
        entityType_ = getDefaultInstance().getEntityType();
        onChanged();
        return this;
      }
      /**
       * <code>string entityType = 2;</code>
       * @param value The bytes for entityType to set.
       * @return This builder for chaining.
       */
      public Builder setEntityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        entityType_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.mqttkotlinsample.ClientIdentity)
    }

    // @@protoc_insertion_point(class_scope:com.example.mqttkotlinsample.ClientIdentity)
    private static final ClientIdentity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientIdentity();
    }

    public static ClientIdentity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientIdentity>
        PARSER = new com.google.protobuf.AbstractParser<ClientIdentity>() {
      @Override
      public ClientIdentity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientIdentity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientIdentity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientIdentity> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientIdentity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoutedMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.mqttkotlinsample.RoutedMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes msgBytes = 1;</code>
     * @return The msgBytes.
     */
    com.google.protobuf.ByteString getMsgBytes();

    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     * @return The position.
     */
    Position getPosition();
    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     */
    PositionOrBuilder getPositionOrBuilder();

    /**
     * <pre>
     * only applies if customRadiusOpt is set
     * </pre>
     *
     * <code>bool clientCanOverrideRadiusOpt = 5;</code>
     * @return The clientCanOverrideRadiusOpt.
     */
    boolean getClientCanOverrideRadiusOpt();

    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    java.util.List<ClientIdentity>
        getClientIdsOptList();
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    ClientIdentity getClientIdsOpt(int index);
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    int getClientIdsOptCount();
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    java.util.List<? extends ClientIdentityOrBuilder>
        getClientIdsOptOrBuilderList();
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    ClientIdentityOrBuilder getClientIdsOptOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.mqttkotlinsample.RoutedMsg}
   */
  public static final class RoutedMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.mqttkotlinsample.RoutedMsg)
      RoutedMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoutedMsg.newBuilder() to construct.
    private RoutedMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoutedMsg() {
      msgBytes_ = com.google.protobuf.ByteString.EMPTY;
      clientIdsOpt_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoutedMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoutedMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              msgBytes_ = input.readBytes();
              break;
            }
            case 26: {
              Position.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              clientCanOverrideRadiusOpt_ = input.readBool();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                clientIdsOpt_ = new java.util.ArrayList<ClientIdentity>();
                mutable_bitField0_ |= 0x00000001;
              }
              clientIdsOpt_.add(
                  input.readMessage(ClientIdentity.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          clientIdsOpt_ = java.util.Collections.unmodifiableList(clientIdsOpt_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Myproto.internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Myproto.internal_static_com_example_mqttkotlinsample_RoutedMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoutedMsg.class, Builder.class);
    }

    public static final int MSGBYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString msgBytes_;
    /**
     * <code>bytes msgBytes = 1;</code>
     * @return The msgBytes.
     */
    @Override
    public com.google.protobuf.ByteString getMsgBytes() {
      return msgBytes_;
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private Position position_;
    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     * @return Whether the position field is set.
     */
    @Override
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     * @return The position.
     */
    @Override
    public Position getPosition() {
      return position_ == null ? Position.getDefaultInstance() : position_;
    }
    /**
     * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
     */
    @Override
    public PositionOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int CLIENTCANOVERRIDERADIUSOPT_FIELD_NUMBER = 5;
    private boolean clientCanOverrideRadiusOpt_;
    /**
     * <pre>
     * only applies if customRadiusOpt is set
     * </pre>
     *
     * <code>bool clientCanOverrideRadiusOpt = 5;</code>
     * @return The clientCanOverrideRadiusOpt.
     */
    @Override
    public boolean getClientCanOverrideRadiusOpt() {
      return clientCanOverrideRadiusOpt_;
    }

    public static final int CLIENTIDSOPT_FIELD_NUMBER = 6;
    private java.util.List<ClientIdentity> clientIdsOpt_;
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    @Override
    public java.util.List<ClientIdentity> getClientIdsOptList() {
      return clientIdsOpt_;
    }
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    @Override
    public java.util.List<? extends ClientIdentityOrBuilder>
        getClientIdsOptOrBuilderList() {
      return clientIdsOpt_;
    }
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    @Override
    public int getClientIdsOptCount() {
      return clientIdsOpt_.size();
    }
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    @Override
    public ClientIdentity getClientIdsOpt(int index) {
      return clientIdsOpt_.get(index);
    }
    /**
     * <pre>
     * if specified, these are the
     * </pre>
     *
     * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
     */
    @Override
    public ClientIdentityOrBuilder getClientIdsOptOrBuilder(
        int index) {
      return clientIdsOpt_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!msgBytes_.isEmpty()) {
        output.writeBytes(1, msgBytes_);
      }
      if (position_ != null) {
        output.writeMessage(3, getPosition());
      }
      if (clientCanOverrideRadiusOpt_ != false) {
        output.writeBool(5, clientCanOverrideRadiusOpt_);
      }
      for (int i = 0; i < clientIdsOpt_.size(); i++) {
        output.writeMessage(6, clientIdsOpt_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!msgBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, msgBytes_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPosition());
      }
      if (clientCanOverrideRadiusOpt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, clientCanOverrideRadiusOpt_);
      }
      for (int i = 0; i < clientIdsOpt_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, clientIdsOpt_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoutedMsg)) {
        return super.equals(obj);
      }
      RoutedMsg other = (RoutedMsg) obj;

      if (!getMsgBytes()
          .equals(other.getMsgBytes())) return false;
      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (getClientCanOverrideRadiusOpt()
          != other.getClientCanOverrideRadiusOpt()) return false;
      if (!getClientIdsOptList()
          .equals(other.getClientIdsOptList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBytes().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + CLIENTCANOVERRIDERADIUSOPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getClientCanOverrideRadiusOpt());
      if (getClientIdsOptCount() > 0) {
        hash = (37 * hash) + CLIENTIDSOPT_FIELD_NUMBER;
        hash = (53 * hash) + getClientIdsOptList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoutedMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoutedMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoutedMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoutedMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoutedMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoutedMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoutedMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoutedMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoutedMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoutedMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoutedMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoutedMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoutedMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.mqttkotlinsample.RoutedMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.mqttkotlinsample.RoutedMsg)
        RoutedMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Myproto.internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Myproto.internal_static_com_example_mqttkotlinsample_RoutedMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoutedMsg.class, Builder.class);
      }

      // Construct using com.example.mqttkotlinsample.Myproto.RoutedMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClientIdsOptFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgBytes_ = com.google.protobuf.ByteString.EMPTY;

        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        clientCanOverrideRadiusOpt_ = false;

        if (clientIdsOptBuilder_ == null) {
          clientIdsOpt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          clientIdsOptBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Myproto.internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor;
      }

      @Override
      public RoutedMsg getDefaultInstanceForType() {
        return RoutedMsg.getDefaultInstance();
      }

      @Override
      public RoutedMsg build() {
        RoutedMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RoutedMsg buildPartial() {
        RoutedMsg result = new RoutedMsg(this);
        int from_bitField0_ = bitField0_;
        result.msgBytes_ = msgBytes_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.clientCanOverrideRadiusOpt_ = clientCanOverrideRadiusOpt_;
        if (clientIdsOptBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            clientIdsOpt_ = java.util.Collections.unmodifiableList(clientIdsOpt_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.clientIdsOpt_ = clientIdsOpt_;
        } else {
          result.clientIdsOpt_ = clientIdsOptBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoutedMsg) {
          return mergeFrom((RoutedMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoutedMsg other) {
        if (other == RoutedMsg.getDefaultInstance()) return this;
        if (other.getMsgBytes() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBytes(other.getMsgBytes());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.getClientCanOverrideRadiusOpt() != false) {
          setClientCanOverrideRadiusOpt(other.getClientCanOverrideRadiusOpt());
        }
        if (clientIdsOptBuilder_ == null) {
          if (!other.clientIdsOpt_.isEmpty()) {
            if (clientIdsOpt_.isEmpty()) {
              clientIdsOpt_ = other.clientIdsOpt_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClientIdsOptIsMutable();
              clientIdsOpt_.addAll(other.clientIdsOpt_);
            }
            onChanged();
          }
        } else {
          if (!other.clientIdsOpt_.isEmpty()) {
            if (clientIdsOptBuilder_.isEmpty()) {
              clientIdsOptBuilder_.dispose();
              clientIdsOptBuilder_ = null;
              clientIdsOpt_ = other.clientIdsOpt_;
              bitField0_ = (bitField0_ & ~0x00000001);
              clientIdsOptBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClientIdsOptFieldBuilder() : null;
            } else {
              clientIdsOptBuilder_.addAllMessages(other.clientIdsOpt_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RoutedMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RoutedMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString msgBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msgBytes = 1;</code>
       * @return The msgBytes.
       */
      @Override
      public com.google.protobuf.ByteString getMsgBytes() {
        return msgBytes_;
      }
      /**
       * <code>bytes msgBytes = 1;</code>
       * @param value The msgBytes to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msgBytes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgBytes() {
        
        msgBytes_ = getDefaultInstance().getMsgBytes();
        onChanged();
        return this;
      }

      private Position position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Position, Position.Builder, PositionOrBuilder> positionBuilder_;
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       * @return The position.
       */
      public Position getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? Position.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public Builder setPosition(Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public Builder setPosition(
          Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public Builder mergePosition(Position value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public Position.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      public PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              Position.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.com.example.mqttkotlinsample.Position position = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Position, Position.Builder, PositionOrBuilder>
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Position, Position.Builder, PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private boolean clientCanOverrideRadiusOpt_ ;
      /**
       * <pre>
       * only applies if customRadiusOpt is set
       * </pre>
       *
       * <code>bool clientCanOverrideRadiusOpt = 5;</code>
       * @return The clientCanOverrideRadiusOpt.
       */
      @Override
      public boolean getClientCanOverrideRadiusOpt() {
        return clientCanOverrideRadiusOpt_;
      }
      /**
       * <pre>
       * only applies if customRadiusOpt is set
       * </pre>
       *
       * <code>bool clientCanOverrideRadiusOpt = 5;</code>
       * @param value The clientCanOverrideRadiusOpt to set.
       * @return This builder for chaining.
       */
      public Builder setClientCanOverrideRadiusOpt(boolean value) {
        
        clientCanOverrideRadiusOpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * only applies if customRadiusOpt is set
       * </pre>
       *
       * <code>bool clientCanOverrideRadiusOpt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientCanOverrideRadiusOpt() {
        
        clientCanOverrideRadiusOpt_ = false;
        onChanged();
        return this;
      }

      private java.util.List<ClientIdentity> clientIdsOpt_ =
        java.util.Collections.emptyList();
      private void ensureClientIdsOptIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          clientIdsOpt_ = new java.util.ArrayList<ClientIdentity>(clientIdsOpt_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientIdentity, ClientIdentity.Builder, ClientIdentityOrBuilder> clientIdsOptBuilder_;

      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public java.util.List<ClientIdentity> getClientIdsOptList() {
        if (clientIdsOptBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clientIdsOpt_);
        } else {
          return clientIdsOptBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public int getClientIdsOptCount() {
        if (clientIdsOptBuilder_ == null) {
          return clientIdsOpt_.size();
        } else {
          return clientIdsOptBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public ClientIdentity getClientIdsOpt(int index) {
        if (clientIdsOptBuilder_ == null) {
          return clientIdsOpt_.get(index);
        } else {
          return clientIdsOptBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder setClientIdsOpt(
          int index, ClientIdentity value) {
        if (clientIdsOptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.set(index, value);
          onChanged();
        } else {
          clientIdsOptBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder setClientIdsOpt(
          int index, ClientIdentity.Builder builderForValue) {
        if (clientIdsOptBuilder_ == null) {
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.set(index, builderForValue.build());
          onChanged();
        } else {
          clientIdsOptBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder addClientIdsOpt(ClientIdentity value) {
        if (clientIdsOptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.add(value);
          onChanged();
        } else {
          clientIdsOptBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder addClientIdsOpt(
          int index, ClientIdentity value) {
        if (clientIdsOptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.add(index, value);
          onChanged();
        } else {
          clientIdsOptBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder addClientIdsOpt(
          ClientIdentity.Builder builderForValue) {
        if (clientIdsOptBuilder_ == null) {
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.add(builderForValue.build());
          onChanged();
        } else {
          clientIdsOptBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder addClientIdsOpt(
          int index, ClientIdentity.Builder builderForValue) {
        if (clientIdsOptBuilder_ == null) {
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.add(index, builderForValue.build());
          onChanged();
        } else {
          clientIdsOptBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder addAllClientIdsOpt(
          Iterable<? extends ClientIdentity> values) {
        if (clientIdsOptBuilder_ == null) {
          ensureClientIdsOptIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clientIdsOpt_);
          onChanged();
        } else {
          clientIdsOptBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder clearClientIdsOpt() {
        if (clientIdsOptBuilder_ == null) {
          clientIdsOpt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          clientIdsOptBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public Builder removeClientIdsOpt(int index) {
        if (clientIdsOptBuilder_ == null) {
          ensureClientIdsOptIsMutable();
          clientIdsOpt_.remove(index);
          onChanged();
        } else {
          clientIdsOptBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public ClientIdentity.Builder getClientIdsOptBuilder(
          int index) {
        return getClientIdsOptFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public ClientIdentityOrBuilder getClientIdsOptOrBuilder(
          int index) {
        if (clientIdsOptBuilder_ == null) {
          return clientIdsOpt_.get(index);  } else {
          return clientIdsOptBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public java.util.List<? extends ClientIdentityOrBuilder>
           getClientIdsOptOrBuilderList() {
        if (clientIdsOptBuilder_ != null) {
          return clientIdsOptBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clientIdsOpt_);
        }
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public ClientIdentity.Builder addClientIdsOptBuilder() {
        return getClientIdsOptFieldBuilder().addBuilder(
            ClientIdentity.getDefaultInstance());
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public ClientIdentity.Builder addClientIdsOptBuilder(
          int index) {
        return getClientIdsOptFieldBuilder().addBuilder(
            index, ClientIdentity.getDefaultInstance());
      }
      /**
       * <pre>
       * if specified, these are the
       * </pre>
       *
       * <code>repeated .com.example.mqttkotlinsample.ClientIdentity clientIdsOpt = 6;</code>
       */
      public java.util.List<ClientIdentity.Builder>
           getClientIdsOptBuilderList() {
        return getClientIdsOptFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientIdentity, ClientIdentity.Builder, ClientIdentityOrBuilder>
          getClientIdsOptFieldBuilder() {
        if (clientIdsOptBuilder_ == null) {
          clientIdsOptBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ClientIdentity, ClientIdentity.Builder, ClientIdentityOrBuilder>(
                  clientIdsOpt_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          clientIdsOpt_ = null;
        }
        return clientIdsOptBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.mqttkotlinsample.RoutedMsg)
    }

    // @@protoc_insertion_point(class_scope:com.example.mqttkotlinsample.RoutedMsg)
    private static final RoutedMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoutedMsg();
    }

    public static RoutedMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoutedMsg>
        PARSER = new com.google.protobuf.AbstractParser<RoutedMsg>() {
      @Override
      public RoutedMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoutedMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoutedMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoutedMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public RoutedMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_mqttkotlinsample_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_mqttkotlinsample_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_mqttkotlinsample_ClientIdentity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_mqttkotlinsample_RoutedMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmyproto.proto\022\034com.example.mqttkotlins" +
      "ample\"/\n\010Position\022\020\n\010latitude\030\001 \001(\005\022\021\n\tl" +
      "ongitude\030\002 \001(\005\"7\n\016ClientIdentity\022\021\n\010clie" +
      "ntId\030\257\001 \001(\r\022\022\n\nentityType\030\002 \001(\t\"\277\001\n\tRout" +
      "edMsg\022\020\n\010msgBytes\030\001 \001(\014\0228\n\010position\030\003 \001(" +
      "\0132&.com.example.mqttkotlinsample.Positio" +
      "n\022\"\n\032clientCanOverrideRadiusOpt\030\005 \001(\010\022B\n" +
      "\014clientIdsOpt\030\006 \003(\0132,.com.example.mqttko" +
      "tlinsample.ClientIdentityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_mqttkotlinsample_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_mqttkotlinsample_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_mqttkotlinsample_Position_descriptor,
        new String[] { "Latitude", "Longitude", });
    internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_mqttkotlinsample_ClientIdentity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_mqttkotlinsample_ClientIdentity_descriptor,
        new String[] { "ClientId", "EntityType", });
    internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_mqttkotlinsample_RoutedMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_mqttkotlinsample_RoutedMsg_descriptor,
        new String[] { "MsgBytes", "Position", "ClientCanOverrideRadiusOpt", "ClientIdsOpt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
